title: [titel here]
description: [course description]
author: [author here]
company: ROC-Midden Nederland
department: ICT-College
education: MBO Niveau 4
location: Amersfoort, Nederland
baseurl: "/template_reader_presentation"
repository: markkors/template_reader_presentation
theme: minima
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-feed